export const ADD_TO_CART = "ADD_TO_CART";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const REMOVE_PRODUCT = "REMOVE_PRODUCT";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const PRODUCT_LOADED = "PRODUCT_LOADED";
export const TOGGLE_STOCK = "TOGGLE_STOCK";
export const TOGGLE_BRAND = "TOGGLE_BRAND";
